workflowVersion: 1.0.0
speakeasyVersion: 1.606.10
sources:
    mistral-azure-source:
        inputs:
            - location: /home/ian/Documents/mistral/mistral-azure.yaml
        registry:
            location: registry.speakeasyapi.dev/ian/ian/mistral-azure-source
    mistral-google-cloud-source:
        inputs:
            - location: /home/ian/Documents/mistral/mistral-google-cloud.yaml
        registry:
            location: registry.speakeasyapi.dev/ian/ian/mistral-google-cloud-source
    mistral-openapi:
        inputs:
            - location: /home/ian/Documents/mistral/mistral.yaml
        registry:
            location: registry.speakeasyapi.dev/ian/ian/mistral-openapi
targets:
    mistralai-azure-sdk:
        target: python
        source: mistral-azure-source
        output: ./packages/mistralai_azure
        publish:
            pypi:
                token: $pypi_token
    mistralai-gcp-sdk:
        target: python
        source: mistral-google-cloud-source
        output: ./packages/mistralai_gcp
        publish:
            pypi:
                token: $pypi_token
    mistralai-sdk:
        target: python
        source: mistral-openapi
        publish:
            pypi:
                token: $pypi_token
